version: '3'
services:
  chrome:
    image: seleniarm/standalone-chromium
    shm_size: '2gb'
    ports:
      - "4444:4444" # Selenium service
      - "5900:5900" # VNC server
      - "7900:7900" # VNC browser client
  firefox:
    image: seleniarm/standalone-firefox
    shm_size: '2gb'
    ports:
      - "4445:4444" # Selenium service
      - "5901:5900" # VNC server
      - "7901:7900" # VNC browser client
